"""
Groq API Integration
Handles content generation using Groq's LLM API
"""
import json
import os
import requests
from typing import Dict, Any
import sys

# Add shared directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'shared'))

from shared.models import EnhancedPrompt


class GroqIntegrationService:
    """Service for integrating with Groq API"""
    
    def __init__(self):
        """Initialize Groq API client"""
        self.api_key = os.environ.get('GROQ_API_KEY')
        if not self.api_key:
            raise ValueError("GROQ_API_KEY environment variable not set")
        
        self.api_url = "https://api.groq.com/openai/v1/chat/completions"
        self.model = "llama-3.3-70b-versatile"  # Updated model
    
    def generate_content(
        self,
        prompt: str,
        temperature: float = 0.7,
        max_tokens: int = 1000,
        top_p: float = 0.9
    ) -> Dict[str, Any]:
        """
        Generate content using Groq API
        
        Args:
            prompt: The formatted prompt to send to Groq
            temperature: Sampling temperature (0-2)
            max_tokens: Maximum tokens to generate
            top_p: Nucleus sampling parameter
            
        Returns:
            Dictionary with generated content and metadata
            
        Raises:
            Exception: If API call fails
        """
        try:
            # Prepare request headers
            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            }
            
            # Prepare request payload
            payload = {
                "model": self.model,
                "messages": [
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                "temperature": temperature,
                "max_tokens": max_tokens,
                "top_p": top_p
            }
            
            # Make API request
            response = requests.post(
                self.api_url,
                headers=headers,
                json=payload,
                timeout=30  # 30 second timeout
            )
            
            # Check for errors
            if response.status_code != 200:
                error_detail = response.text
                raise Exception(f"Groq API error (status {response.status_code}): {error_detail}")
            
            # Parse response
            response_data = response.json()
            
            # Extract generated content
            if 'choices' not in response_data or len(response_data['choices']) == 0:
                raise Exception("No content generated by Groq API")
            
            generated_text = response_data['choices'][0]['message']['content']
            
            # Extract metadata
            usage = response_data.get('usage', {})
            
            return {
                "success": True,
                "generated_text": generated_text,
                "model_used": self.model,
                "tokens_used": usage.get('total_tokens', 0),
                "prompt_tokens": usage.get('prompt_tokens', 0),
                "completion_tokens": usage.get('completion_tokens', 0),
                "finish_reason": response_data['choices'][0].get('finish_reason', 'unknown')
            }
            
        except requests.exceptions.Timeout:
            raise Exception("Groq API request timed out after 30 seconds")
        except requests.exceptions.RequestException as e:
            raise Exception(f"Groq API request failed: {str(e)}")
        except Exception as e:
            raise Exception(f"Failed to generate content with Groq: {str(e)}")
    
    def validate_response(self, generated_text: str) -> Dict[str, Any]:
        """
        Validate the generated response
        
        Args:
            generated_text: The generated text to validate
            
        Returns:
            Validation results
        """
        validation = {
            "is_valid": True,
            "issues": []
        }
        
        # Check if text is empty
        if not generated_text or len(generated_text.strip()) == 0:
            validation["is_valid"] = False
            validation["issues"].append("Generated text is empty")
        
        # Check minimum length
        if len(generated_text.strip()) < 10:
            validation["is_valid"] = False
            validation["issues"].append("Generated text is too short")
        
        # Check for common error patterns
        error_patterns = [
            "I cannot",
            "I'm unable to",
            "I don't have access",
            "As an AI"
        ]
        
        for pattern in error_patterns:
            if pattern.lower() in generated_text.lower()[:100]:  # Check first 100 chars
                validation["issues"].append(f"Response contains error pattern: {pattern}")
        
        return validation


def handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    Lambda handler for Groq API integration
    
    Args:
        event: API Gateway event with prompt and parameters
        context: Lambda context
        
    Returns:
        API Gateway response with generated content
    """
    try:
        # Parse request body
        body = json.loads(event.get("body", "{}"))
        
        # Validate required fields
        if "prompt" not in body:
            return {
                "statusCode": 400,
                "headers": {"Content-Type": "application/json"},
                "body": json.dumps({
                    "error": "Missing required field: prompt"
                })
            }
        
        prompt = body["prompt"]
        temperature = body.get("temperature", 0.7)
        max_tokens = body.get("max_tokens", 1000)
        top_p = body.get("top_p", 0.9)
        
        # Initialize Groq service
        groq_service = GroqIntegrationService()
        
        # Generate content
        result = groq_service.generate_content(
            prompt=prompt,
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=top_p
        )
        
        # Validate response
        validation = groq_service.validate_response(result["generated_text"])
        
        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "success": True,
                "generated_text": result["generated_text"],
                "model_used": result["model_used"],
                "tokens_used": result["tokens_used"],
                "validation": validation
            })
        }
        
    except Exception as e:
        return {
            "statusCode": 500,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "error": f"Internal server error: {str(e)}"
            })
        }
